version: "{build}"

platform: x64

branches:
    only:
      - master
      - develop

skip_tags: true

matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - ps: Install-Product node 5
  - cmd: npm install

build_script:
  - cmd: mkdir grammars
  - cmd: node node_modules/.bin/yaml2json --pretty 1c.YAML-tmLanguage > 1c.json
  - cmd: node node_modules/.bin/yaml2json --pretty 1c-query.YAML-tmLanguage > 1c-query.json
  - cmd: node node_modules/.bin/json2cson 1c.json > grammars/1c.cson --2spaces
  - cmd: node node_modules/.bin/json2cson 1c-query.json > grammars/1c-query.cson --2spaces
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
